<?php

use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run()
    {
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (1, 'Leticia', 1);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (2, 'Puerto Nariño', 1);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (3, 'Caldas', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (4, 'Tarazá', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (5, 'La Estrella', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (6, 'Anorí', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (7, 'Santa Rosa de Osos', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (8, 'San Roque', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (9, 'Retiro', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (10, 'Betulia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (11, 'Sonsón', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (12, 'Copacabana', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (13, 'Yondó', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (14, 'Santo Domingo', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (15, 'Sabaneta', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (16, 'Chigorodó', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (17, 'Abejorral', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (18, 'Valdivia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (19, 'Angostura', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (20, 'Caucasia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (21, 'Salgar', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (22, 'Santuario', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (23, 'Venecia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (24, 'Yarumal', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (25, 'Granada', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (26, 'San Vicente', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (27, 'Vegachí', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (28, 'Sabanalarga', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (29, 'La Unión', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (30, 'Apartadó', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (31, 'Yarumal', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (32, 'Carepa', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (33, 'Cañasgordas', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (34, 'Urrao', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (35, 'Jardín', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (36, 'Arboletes', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (37, 'Guarne', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (38, 'Girardota', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (39, 'El Bagre', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (40, 'San Jerónimo', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (41, 'Andes', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (42, 'Barbosa', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (43, 'San Rafael', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (44, 'Cáceres', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (45, 'Titiribí', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (46, 'Medellín', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (47, 'Puerto Nare', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (48, 'Ebéjico', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (49, 'Sopetrán', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (50, 'Jericó', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (51, 'San Carlos', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (52, 'Segovia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (53, 'Carmen de Viboral', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (54, 'Cocorná', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (55, 'Marinilla', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (56, 'La Ceja', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (57, 'Támesis', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (58, 'Necoclí', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (59, 'Puerto Berrío', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (60, 'Cisneros', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (61, 'Ciudad Bolívar', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (62, 'Briceño', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (63, 'Mutatá', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (64, 'Santa Fe de Antioquia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (65, 'Entrerríos', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (66, 'Valdivia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (67, 'Amalfi', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (68, 'Turbo', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (69, 'Dabeiba', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (70, 'Betania', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (71, 'Donmatías', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (72, 'Frontino', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (73, 'San Juan de Urabá', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (74, 'Envigado', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (75, 'Itagüí', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (76, 'Guatapé', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (77, 'Argelia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (78, 'Zaragoza', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (79, 'Campamento', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (80, 'Angelópolis', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (81, 'Ituango', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (82, 'Amagá', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (83, 'Nechí', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (84, 'Yolombó', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (85, 'San Pedro de Urabá', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (86, 'Concordia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (87, 'Remedios', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (88, 'Fredonia', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (89, 'Yalí', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (90, 'Rionegro', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (91, 'Nariño', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (92, 'Santa Bárbara', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (93, 'Bello', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (94, 'Puerto Triunfo', 2);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (95, 'Fortul', 3);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (96, 'Arauquita', 3);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (97, 'Saravena', 3);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (98, 'Arauca', 3);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (99, 'Tame', 3);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (100, 'Polonuevo', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (101, 'Manatí', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (102, 'Barranquilla', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (103, 'Usiacurí', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (104, 'Baranoa', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (105, 'Galapa', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (106, 'Soledad', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (107, 'Juan de Acosta', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (108, 'Puerto Colombia', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (109, 'Sabanagrande', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (110, 'Ponedera', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (111, 'Candelaria', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (112, 'Santa Lucía', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (113, 'Palmar de Varela', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (114, 'Campo de la Cruz', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (115, 'Santo Tomás', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (116, 'Malambo', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (117, 'Sabanalarga', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (118, 'Luruaco', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (119, 'Suan', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (120, 'Repelón', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (121, 'Tubará', 4);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (122, 'Fontibón', 5);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (123, 'Bogotá', 5);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (124, 'Usme', 5);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (125, 'Simití', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (126, 'San Martín de Loba', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (127, 'Pinillos', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (128, 'Morales', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (129, 'Altos del Rosario', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (130, 'Santa Rosa', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (131, 'Clemencia', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (132, 'San Juan Nepomuceno', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (133, 'Villanueva', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (134, 'Barranco de Loba', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (135, 'Santa Rosa del Sur', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (136, 'Mahates', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (137, 'Santa Catalina', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (138, 'Montecristo', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (139, 'Achí', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (140, 'San Jacinto', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (141, 'San Estanislao', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (142, 'Calamar', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (143, 'Tiquisio', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (144, 'San Pablo', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (145, 'Turbaco', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (146, 'Regidor', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (147, 'Arjona', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (148, 'Turbaná', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (149, 'Talaigua Nuevo', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (150, 'Norosí', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (151, 'San Fernando', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (152, 'Zambrano', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (153, 'San Fernando', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (154, 'El Carmen de Bolívar', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (155, 'Cartagena', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (156, 'Margarita', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (157, 'Córdoba', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (158, 'Hatillo de Loba', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (159, 'Magangué', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (160, 'Cicuco', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (161, 'San Jacinto del Cauca', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (162, 'María la Baja', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (163, 'Arroyohondo', 6);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (164, 'Villa de Leyva', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (165, 'Guateque', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (166, 'Cómbita', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (167, 'Duitama', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (168, 'Tuta', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (169, 'Ramiriquí', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (170, 'Garagoa', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (171, 'Ráquira', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (172, 'Sogamoso', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (173, 'Siachoque', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (174, 'Santa Rosa de Viterbo', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (175, 'Ventaquemada', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (176, 'Samacá', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (177, 'Aquitania', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (178, 'Nobsa', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (179, 'Moniquirá', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (180, 'Toca', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (181, 'Socotá', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (182, 'Pesca', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (183, 'Chiquinquirá', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (184, 'Chita', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (185, 'Úmbita', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (186, 'Saboyá', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (187, 'Tibasosa', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (188, 'Puerto Boyacá', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (189, 'Tibaná', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (190, 'Tunja', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (191, 'Muzo', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (192, 'Paipa', 7);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (193, 'Samaná', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (194, 'Palestina', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (195, 'La Dorada', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (196, 'Anserma', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (197, 'Supía', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (198, 'Aranzazu', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (199, 'Risaralda', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (200, 'Manzanares', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (201, 'Manizales', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (202, 'Viterbo', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (203, 'Chinchiná', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (204, 'Marquetalia', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (205, 'Villamaría', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (206, 'Pácora', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (207, 'Riosucio', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (208, 'Filadelfia', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (209, 'Belalcázar', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (210, 'Aguadas', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (211, 'Salamina', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (212, 'Pensilvania', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (213, 'Neira', 8);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (214, 'Puerto Rico', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (215, 'Cartagena del Chairá', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (216, 'Belén de los Andaquíes', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (217, 'San Vicente del Caguán', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (218, 'San José del Fragua', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (219, 'La Montañita', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (220, 'El Paujíl', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (221, 'Solano', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (222, 'El Doncello', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (223, 'Florencia', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (224, 'Solita', 9);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (225, 'Tauramena', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (226, 'Nunchía', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (227, 'Paz de Ariporo', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (228, 'Yopal', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (229, 'Aguazul', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (230, 'Orocué', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (231, 'Monterrey', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (232, 'Trinidad', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (233, 'Villanueva', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (234, 'Maní', 10);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (235, 'Caloto', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (236, 'La Vega', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (237, 'Almaguer', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (238, 'Coconuco', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (239, 'Rosas', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (240, 'Timbío', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (241, 'Balboa', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (242, 'Paispamba', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (243, 'Timbiquí', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (244, 'Guapí', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (245, 'Villa Rica', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (246, 'Miranda', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (247, 'Santander de Quilichao', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (248, 'Mercaderes', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (249, 'Piamonte', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (250, 'Argelia', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (251, 'Piendamó', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (252, 'Bolívar', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (253, 'Puerto Tejada', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (254, 'Popayán', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (255, 'Morales', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (256, 'Corinto', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (257, 'Inzá', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (258, 'Cajibío', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (259, 'Sucre', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (260, 'Buenos Aires', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (261, 'Villa Rica', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (262, 'Caldono', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (263, 'Totoró', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (264, 'Padilla', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (265, 'Belalcázar', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (266, 'La Sierra', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (267, 'Silvia', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (268, 'El Bordo', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (269, 'Patía', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (270, 'Jambaló', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (271, 'San Sebastián', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (272, 'Suárez', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (273, 'Toribío', 11);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (274, 'La Jagua de Ibirico', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (275, 'Pueblo Bello', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (276, 'Tamalameque', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (277, 'Chiriguaná', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (278, 'El Paso', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (279, 'Aguachica', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (280, 'San Alberto', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (281, 'Valledupar', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (282, 'San Diego', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (283, 'González', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (284, 'Astrea', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (285, 'Agustín Codazzi', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (286, 'Curumaní', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (287, 'Río de Oro', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (288, 'Gamarra', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (289, 'El Copey', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (290, 'Pelaya', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (291, 'Pailitas', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (292, 'San Martín', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (293, 'Bosconia', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (294, 'Becerril', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (295, 'La Gloria', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (296, 'Chimichagua', 12);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (297, 'Juradó', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (298, 'Nuquí', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (299, 'Mutis', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (300, 'Tadó', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (301, 'Pizarro', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (302, 'Bellavista', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (303, 'Lloró', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (304, 'Santa Genoveva de Docordó', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (305, 'Condoto', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (306, 'Acandí', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (307, 'Unguía', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (308, 'El Carmen de Atrato', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (309, 'Bagadó', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (310, 'Quibdó', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (311, 'Pie de Pató', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (312, 'Riosucio', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (313, 'Istmina', 13);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (314, 'Pueblo Nuevo', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (315, 'Buenavista', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (316, 'Tuchín', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (317, 'La Apartada', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (318, 'Cotorra', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (319, 'Momil', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (320, 'San Bernardo del Viento', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (321, 'Buenavista', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (322, 'San Antero', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (323, 'Puerto Escondido', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (324, 'Montería', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (325, 'Moñitos', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (326, 'San Carlos', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (327, 'Purísima de la Concepción', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (328, 'San Pelayo', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (329, 'Valencia', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (330, 'Ayapel', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (331, 'San Andrés de Sotavento', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (332, 'Chimá', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (333, 'Chinú', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (334, 'Lorica', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (335, 'Puerto Libertador', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (336, 'Ciénaga de Oro', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (337, 'Planeta Rica', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (338, 'Tierralta', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (339, 'Montelíbano', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (340, 'Sahagún', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (341, 'Cereté', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (342, 'Canalete', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (343, 'Los Córdobas', 14);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (344, 'Cogua', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (345, 'Sesquilé', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (346, 'Nemocón', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (347, 'El Rosal', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (348, 'La Vega', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (349, 'Pacho', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (350, 'Soacha', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (351, 'San Antonio del Tequendama', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (352, 'Simijaca', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (353, 'La Mesa', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (354, 'Anolaima', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (355, 'Ricaurte', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (356, 'Cota', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (357, 'Viotá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (358, 'Tenjo', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (359, 'Cajicá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (360, 'Susa', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (361, 'Zipaquirá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (362, 'Fómeque', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (363, 'Villa de San Diego de Ubaté', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (364, 'Tocancipá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (365, 'Suesca', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (366, 'Tena', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (367, 'Cáqueza', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (368, 'Gachancipá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (369, 'Subachoque', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (370, 'Sibaté', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (371, 'Guasca', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (372, 'Puerto Salgar', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (373, 'Bojacá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (374, 'Carmen de Carupa', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (375, 'Anapoima', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (376, 'Guaduas', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (377, 'Une', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (378, 'Villeta', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (379, 'Tocaima', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (380, 'Granada', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (381, 'Arbeláez', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (382, 'El Colegio', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (383, 'Ubalá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (384, 'Junín', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (385, 'Caparrapí', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (386, 'Tausa', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (387, 'Sopó', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (388, 'Silvania', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (389, 'Lenguazaque', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (390, 'La Calera', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (391, 'Medina', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (392, 'Funza', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (393, 'Facatativá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (394, 'Madrid', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (395, 'Chía', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (396, 'Mosquera', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (397, 'Cachipay', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (398, 'Sasaima', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (399, 'Girardot', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (400, 'Chocontá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (401, 'Yacopí', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (402, 'Pasca', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (403, 'Fusagasugá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (404, 'Villapinzón', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (405, 'Guachetá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (406, 'Tabio', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (407, 'La Palma', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (408, 'Choachí', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (409, 'Agua de Dios', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (410, 'Gachetá', 15);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (411, 'Inírida', 16);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (412, 'El Retorno', 17);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (413, 'San José del Guaviare', 17);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (414, 'Calamar', 17);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (415, 'Tarqui', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (416, 'Tesalia', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (417, 'Pital', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (418, 'Yaguará', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (419, 'Algeciras', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (420, 'Palermo', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (421, 'Íquira', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (422, 'La Plata', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (423, 'Oporapa', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (424, 'Pitalito', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (425, 'Saladoblanco', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (426, 'La Argentina', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (427, 'Acevedo', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (428, 'Tello', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (429, 'Garzón', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (430, 'Santa María', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (431, 'Palestina', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (432, 'Guadalupe', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (433, 'Campoalegre', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (434, 'San Agustín', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (435, 'Suaza', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (436, 'Teruel', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (437, 'Aipe', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (438, 'Timaná', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (439, 'Isnos', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (440, 'Gigante', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (441, 'Rivera', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (442, 'Neiva', 18);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (443, 'Maicao', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (444, 'Distracción', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (445, 'Urumita', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (446, 'Albania', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (447, 'Manaure', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (448, 'Barrancas', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (449, 'Hatonuevo', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (450, 'Ríohacha', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (451, 'Dibulla', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (452, 'San Juan del Cesar', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (453, 'Villanueva', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (454, 'Fonseca', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (455, 'Uripa', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (456, 'Uribia', 19);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (457, 'Aracataca', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (458, 'Buenavista', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (459, 'San Zenón', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (460, 'Puebloviejo', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (461, 'Santa Bárbara de Pinto', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (462, 'El Banco', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (463, 'Tenerife', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (464, 'Algarrobo', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (465, 'Algarrobo', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (466, 'Plato', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (467, 'El Retén', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (468, 'Sitionuevo', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (469, 'Pivijay', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (470, 'San Antonio', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (471, 'El Difícil', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (472, 'Santa Ana', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (473, 'San Sebastián de Buenavista', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (474, 'Ciénaga', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (475, 'Fundación', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (476, 'Guamal', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (477, 'Santa Marta', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (478, 'Pijiño del Carmen', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (479, 'Tíogollo', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (480, 'Concordia', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (481, 'Chivolo', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (482, 'El Piñón', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (483, 'Nueva Granada', 20);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (484, 'Puerto Concordia', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (485, 'Cumaral', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (486, 'Puerto López', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (487, 'Puerto Gaitán', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (488, 'Guamal', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (489, 'Puerto Lleras', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (490, 'Castilla La Nueva', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (491, 'Mesetas', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (492, 'La Macarena', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (493, 'Restrepo', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (494, 'Villavicencio', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (495, 'San Martín', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (496, 'Acacías', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (497, 'San Juan de Arama', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (498, 'Hato Corozal', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (499, 'Puerto Rico', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (500, 'San Carlos de Guaroa', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (501, 'Vistahermosa', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (502, 'Lejanías', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (503, 'Fuente de Oro', 21);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (504, 'El Tablón', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (505, 'San José', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (506, 'Bocas de Satinga', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (507, 'Ospina', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (508, 'Ipiales', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (509, 'San Pablo', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (510, 'El Tambo', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (511, 'Carlosama', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (512, 'San Bernardo', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (513, 'Iles', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (514, 'Guaitarilla', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (515, 'Chachagüí', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (516, 'Taminango', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (517, 'Sandoná', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (518, 'San Lorenzo', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (519, 'Guachavés', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (520, 'Yacuanquer', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (521, 'Génova', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (522, 'Potosí', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (523, 'Sotomayor', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (524, 'Mosquera', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (525, 'Consacá', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (526, 'Barbacoas', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (527, 'El Peñol', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (528, 'Ricaurte', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (529, 'Córdoba', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (530, 'La Florida', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (531, 'Guachucal', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (532, 'Pupiales', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (533, 'Iscuandé', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (534, 'Buesaco', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (535, 'San José', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (536, 'La Cruz', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (537, 'La Unión', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (538, 'Cumbal', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (539, 'Samaniego', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (540, 'Linares', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (541, 'El Charco', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (542, 'Pasto', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (543, 'Túquerres', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (544, 'Tumaco', 22);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (545, 'Tarrá', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (546, 'Cáchira', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (547, 'El Carmen', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (548, 'La Esperanza', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (549, 'Villa del Rosario', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (550, 'Cúcuta', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (551, 'Teorama', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (552, 'El Tarra', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (553, 'Ábrego', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (554, 'Convención', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (555, 'Chitagá', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (556, 'Chinácota', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (557, 'Puerto Santander', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (558, 'Los Patios', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (559, 'Arboledas', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (560, 'Tibú', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (561, 'San Calixto', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (562, 'Ocaña', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (563, 'Toledo', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (564, 'Hacarí', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (565, 'Sardinata', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (566, 'Pamplona', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (567, 'El Zulia', 23);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (568, 'Villagarzón', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (569, 'Valle del Guamuez', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (570, 'Puerto Guzmán', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (571, 'Sibundoy', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (572, 'Puerto Asís', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (573, 'Mocoa', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (574, 'Puerto Leguízamo', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (575, 'La Dorada', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (576, 'Puerto Caicedo', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (577, 'Puerto Guzmán', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (578, 'Orito', 24);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (579, 'Calarcá', 25);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (580, 'La Tebaida', 25);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (581, 'Quimbaya', 25);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (582, 'Armenia', 25);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (583, 'Filandia', 25);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (584, 'Circasia', 25);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (585, 'Montenegro', 25);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (586, 'Apía', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (587, 'Guática', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (588, 'Mistrató', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (589, 'Pueblo Rico', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (590, 'La Virginia', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (591, 'Belén de Umbría', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (592, 'Dosquebradas', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (593, 'Santuario', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (594, 'Quinchía', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (595, 'Santa Rosa de Cabal', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (596, 'Marsella', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (597, 'Pereira', 26);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (598, 'San Andrés', 27);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (599, 'Charalá', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (600, 'El Carmen de Chucurí', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (601, 'San Vicente de Chucurí', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (602, 'Sucre', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (603, 'Málaga', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (604, 'La Belleza', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (605, 'Cimitarra', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (606, 'Los Santos', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (607, 'Suaita', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (608, 'Bucaramanga', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (609, 'San Gil', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (610, 'Piedecuesta', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (611, 'Sabana de Torres', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (612, 'Floridablanca', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (613, 'Puerto Wilches', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (614, 'Landázuri', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (615, 'Barbosa', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (616, 'Socorro', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (617, 'Zapatoca', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (618, 'Puente Nacional', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (619, 'El Playón', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (620, 'Oiba', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (621, 'Vélez', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (622, 'Barrancabermeja', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (623, 'Mogotes', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (624, 'Curití', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (625, 'Bolívar', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (626, 'Girón', 28);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (627, 'San Juan de Betulia', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (628, 'Sucre', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (629, 'Caimito', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (630, 'Majagual', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (631, 'Corozal', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (632, 'San Onofre', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (633, 'La Unión', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (634, 'Sincelejo', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (635, 'Morroa', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (636, 'Guaranda', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (637, 'San Marcos', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (638, 'El Roble', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (639, 'Palmito', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (640, 'Galeras', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (641, 'Buenavista', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (642, 'Santiago de Tolú', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (643, 'San Pedro', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (644, 'San Benito Abad', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (645, 'Los Palmitos', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (646, 'Sampués', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (647, 'Ovejas', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (648, 'San Luis de Sincé', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (649, 'Tolú Viejo', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (650, 'Coveñas', 29);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (651, 'Falan', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (652, 'Ibagué', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (653, 'Chaparral', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (654, 'Alvarado', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (655, 'Palocabildo', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (656, 'Cunday', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (657, 'Carmen de Apicalá', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (658, 'Ortega', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (659, 'Lérida', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (660, 'Cajamarca', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (661, 'Melgar', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (662, 'San Sebastián de Mariquita', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (663, 'Líbano', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (664, 'Anzoátegui', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (665, 'Venadillo', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (666, 'Rovira', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (667, 'San Antonio', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (668, 'Saldaña', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (669, 'Guamo', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (670, 'Planadas', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (671, 'Fresno', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (672, 'Purificación', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (673, 'Flandes', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (674, 'Coello', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (675, 'Guayabal', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (676, 'Rioblanco', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (677, 'Natagaima', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (678, 'Coyaima', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (679, 'Icononzo', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (680, 'Espinal', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (681, 'Villahermosa', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (682, 'Ataco', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (683, 'Honda', 30);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (684, 'Jamundí', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (685, 'Guacarí', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (686, 'El Dovio', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (687, 'San Pedro', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (688, 'Buenaventura', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (689, 'Andalucía', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (690, 'Trujillo', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (691, 'Roldanillo', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (692, 'Ansermanuevo', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (693, 'Bugalagrande', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (694, 'Cali', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (695, 'Caicedonia', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (696, 'Ginebra', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (697, 'Bolívar', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (698, 'Guadalajara de Buga', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (699, 'Candelaria', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (700, 'Cartago', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (701, 'El Cairo', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (702, 'Yumbo', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (703, 'Vijes', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (704, 'El Águila', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (705, 'Florida', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (706, 'Pradera', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (707, 'El Cerrito', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (708, 'Alcalá', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (709, 'La Victoria', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (710, 'Zarzal', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (711, 'Palmira', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (712, 'Tuluá', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (713, 'Sevilla', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (714, 'Riofrío', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (715, 'La Unión', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (716, 'Obando', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (717, 'Darién', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (718, 'Restrepo', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (719, 'Yotoco', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (720, 'Toro', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (721, 'Dagua', 31);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (722, 'Mitú', 32);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (723, 'Cumaribo', 33);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (724, 'La Primavera', 33);");
        DB::insert("INSERT INTO `inxaitcorp.game`.`cities` (`id`, `name`, `department_id`) VALUES (725, 'Puerto Carreño', 33);");
    }
}
